JETSON_NANO_DEV_KIT = "JETSON_NANO_DEV_KIT"
UBUNTU_64 = "UBUNTU_64"
UNKNOWN_MODEL = "UNKNOWN_MODEL"

COMPLIANT_MODELS = [JETSON_NANO_DEV_KIT, UBUNTU_64]


# ERRORS
ERROR_MODEL_NOT_SUPPORTED = "Error: Model not supported"
ERROR_WHILE_READING_VALUE = "Error: While reading value"